name: Terraform Plan

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/**"

jobs:
  plan:
    runs-on: [self-hosted, linux, x64]

    defaults:
      run:
        working-directory: terraform

    env:
      TF_VAR_proxmox_endpoint: ${{ secrets.PROXMOX_ENDPOINT }}
      TF_VAR_proxmox_api_token: ${{ secrets.PROXMOX_API_TOKEN }}
      TF_VAR_proxmox_node_name: ${{ secrets.PROXMOX_NODE_NAME }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_lxc_template_file_id: ${{ secrets.LXC_TEMPLATE_FILE_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_EC2_METADATA_DISABLED: "true"

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
      - name: Debug token id
        run: |
            echo "$TF_VAR_proxmox_api_token" | cut -d= -f1

      - run: terraform init
      - run: terraform fmt -check
      - run: terraform validate
      - run: terraform plan
      - run: terraform apply -auto-approve
