name: Terraform Plan

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/**"

jobs:
  plan:
    runs-on: [self-hosted, linux, x64, homelab]

    defaults:
      run:
        working-directory: terraform

    env:
      TF_VAR_proxmox_endpoint: ${{ secrets.PROXMOX_ENDPOINT }}
      TF_VAR_proxmox_api_token: ${{ secrets.PROXMOX_API_TOKEN }}
      TF_VAR_proxmox_node_name: ${{ secrets.PROXMOX_NODE_NAME }}
      TF_VAR_vm_template_id: ${{ secrets.VM_TEMPLATE_ID }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform fmt -check
      - run: terraform validate
      - run: terraform plan